### PR TITLE
Improve the format and enhance the reading experience

### PR DESCRIPTION
**Pull request by Rome2020**
I found the content of this document to be very helpful, but the **formatting issues** affected the reading experience.

So I modified the format to improve the reading experience.

Other parts are in progress, eg:
- Catalog
- ...

### CODE REVIEW

**Comment by SpiralBL0CK** [comment]
hmm give a couple a days like 3 or 4 to take a look at it so i can see it's content is ok again and shure will gratefully merge it :) it will take a little bit longer as i am currently full with learning for the an exam :) but i promise i will find some time to merge it :)

**Comment by Rome2020** [comment]
I understand your schedule, because the exam is more important.

I also respect your content, which is also very important.

But having well-structured documentation helps to read and understand, and that's what I do.

**Comment by SpiralBL0CK** [comment]
I am aware of the formatting issue , and believe me when I say that I am more than thankful for what you have done as you have taken care of one of the main issues of this project . And looking forward to cooperating with you in the near future but what I mean with previous comment is this : the way I structured the article is that I have left some markers for me which are in Romanian my native language so I can know from where to start patching stuff, since the project is big , and I plan to keep updating it regularly. And such that would be why I would like to review the branch first and make sure everything is ok s:)
ps. Again thx a lot for taking care of one of the issues :) Much appreciation

**Comment by Rome2020** [comment]
I'm very happy that what I did helped and I still hope you can write this content in your own style 😜

You can stop replying to me for now.

Congratulations in advance on your exams! 🎉

**Comment by SpiralBL0CK** [comment]
hey sorry i didn't manage to look over just finished the exam failed it tho :/ i will take a look these days over it since i got some free time

**Comment by SpiralBL0CK** [comment]
Hey for a short period of time i'm done with the exams and whatever else,  thx for the improvment . Ps sry it tooks so much time to merge the branch :) Problem is i don't know from where to pick up the research . I completelly forgot what i had in mind when i was doing this

**Comment by SpiralBL0CK** [comment]
I will try to add more content but bare with me as i have to do again a battle plan to pick it up :) it's hard

**Comment by Rome2020** [comment]
keep your rhythm. ♥

**Pull request merged**
